/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include <math.h>

#include "helloworld_types.h"
#include <thrift/c_glib/thrift.h>

/* constants */

enum _HelloWorldServiceSayHelloArgsProperties
{
  PROP_HELLO_WORLD_SERVICE_SAY_HELLO_ARGS_0,
  PROP_HELLO_WORLD_SERVICE_SAY_HELLO_ARGS_NAME
};

/* reads a hello_world_service_say_hello_args object */
static gint32
hello_world_service_say_hello_args_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  HelloWorldServiceSayHelloArgs * this_object = HELLO_WORLD_SERVICE_SAY_HELLO_ARGS(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_STRING)
        {
          if (this_object->name != NULL)
          {
            g_free(this_object->name);
            this_object->name = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->name, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_name = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
hello_world_service_say_hello_args_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  HelloWorldServiceSayHelloArgs * this_object = HELLO_WORLD_SERVICE_SAY_HELLO_ARGS(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "HelloWorldServiceSayHelloArgs", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "name", T_STRING, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->name, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
hello_world_service_say_hello_args_set_property (GObject *object,
                                                 guint property_id,
                                                 const GValue *value,
                                                 GParamSpec *pspec)
{
  HelloWorldServiceSayHelloArgs *self = HELLO_WORLD_SERVICE_SAY_HELLO_ARGS (object);

  switch (property_id)
  {
    case PROP_HELLO_WORLD_SERVICE_SAY_HELLO_ARGS_NAME:
      if (self->name != NULL)
        g_free (self->name);
      self->name = g_value_dup_string (value);
      self->__isset_name = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
hello_world_service_say_hello_args_get_property (GObject *object,
                                                 guint property_id,
                                                 GValue *value,
                                                 GParamSpec *pspec)
{
  HelloWorldServiceSayHelloArgs *self = HELLO_WORLD_SERVICE_SAY_HELLO_ARGS (object);

  switch (property_id)
  {
    case PROP_HELLO_WORLD_SERVICE_SAY_HELLO_ARGS_NAME:
      g_value_set_string (value, self->name);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
hello_world_service_say_hello_args_instance_init (HelloWorldServiceSayHelloArgs * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->name = NULL;
  object->__isset_name = FALSE;
}

static void 
hello_world_service_say_hello_args_finalize (GObject *object)
{
  HelloWorldServiceSayHelloArgs *tobject = HELLO_WORLD_SERVICE_SAY_HELLO_ARGS (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->name != NULL)
  {
    g_free(tobject->name);
    tobject->name = NULL;
  }
}

static void
hello_world_service_say_hello_args_class_init (HelloWorldServiceSayHelloArgsClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = hello_world_service_say_hello_args_read;
  struct_class->write = hello_world_service_say_hello_args_write;

  gobject_class->finalize = hello_world_service_say_hello_args_finalize;
  gobject_class->get_property = hello_world_service_say_hello_args_get_property;
  gobject_class->set_property = hello_world_service_say_hello_args_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_HELLO_WORLD_SERVICE_SAY_HELLO_ARGS_NAME,
     g_param_spec_string ("name",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));
}

GType
hello_world_service_say_hello_args_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (HelloWorldServiceSayHelloArgsClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) hello_world_service_say_hello_args_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (HelloWorldServiceSayHelloArgs),
      0, /* n_preallocs */
      (GInstanceInitFunc) hello_world_service_say_hello_args_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "HelloWorldServiceSayHelloArgsType",
                                   &type_info, 0);
  }

  return type;
}

enum _HelloWorldServiceSayHelloResultProperties
{
  PROP_HELLO_WORLD_SERVICE_SAY_HELLO_RESULT_0,
  PROP_HELLO_WORLD_SERVICE_SAY_HELLO_RESULT_SUCCESS
};

/* reads a hello_world_service_say_hello_result object */
static gint32
hello_world_service_say_hello_result_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  HelloWorldServiceSayHelloResult * this_object = HELLO_WORLD_SERVICE_SAY_HELLO_RESULT(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 0:
        if (ftype == T_STRING)
        {
          if (this_object->success != NULL)
          {
            g_free(this_object->success);
            this_object->success = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->success, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_success = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
hello_world_service_say_hello_result_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  HelloWorldServiceSayHelloResult * this_object = HELLO_WORLD_SERVICE_SAY_HELLO_RESULT(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "HelloWorldServiceSayHelloResult", error)) < 0)
    return -1;
  xfer += ret;
  if (this_object->__isset_success == TRUE) {
    if ((ret = thrift_protocol_write_field_begin (protocol, "success", T_STRING, 0, error)) < 0)
      return -1;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, this_object->success, error)) < 0)
      return -1;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
hello_world_service_say_hello_result_set_property (GObject *object,
                                                   guint property_id,
                                                   const GValue *value,
                                                   GParamSpec *pspec)
{
  HelloWorldServiceSayHelloResult *self = HELLO_WORLD_SERVICE_SAY_HELLO_RESULT (object);

  switch (property_id)
  {
    case PROP_HELLO_WORLD_SERVICE_SAY_HELLO_RESULT_SUCCESS:
      if (self->success != NULL)
        g_free (self->success);
      self->success = g_value_dup_string (value);
      self->__isset_success = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
hello_world_service_say_hello_result_get_property (GObject *object,
                                                   guint property_id,
                                                   GValue *value,
                                                   GParamSpec *pspec)
{
  HelloWorldServiceSayHelloResult *self = HELLO_WORLD_SERVICE_SAY_HELLO_RESULT (object);

  switch (property_id)
  {
    case PROP_HELLO_WORLD_SERVICE_SAY_HELLO_RESULT_SUCCESS:
      g_value_set_string (value, self->success);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
hello_world_service_say_hello_result_instance_init (HelloWorldServiceSayHelloResult * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->success = NULL;
  object->__isset_success = FALSE;
}

static void 
hello_world_service_say_hello_result_finalize (GObject *object)
{
  HelloWorldServiceSayHelloResult *tobject = HELLO_WORLD_SERVICE_SAY_HELLO_RESULT (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->success != NULL)
  {
    g_free(tobject->success);
    tobject->success = NULL;
  }
}

static void
hello_world_service_say_hello_result_class_init (HelloWorldServiceSayHelloResultClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = hello_world_service_say_hello_result_read;
  struct_class->write = hello_world_service_say_hello_result_write;

  gobject_class->finalize = hello_world_service_say_hello_result_finalize;
  gobject_class->get_property = hello_world_service_say_hello_result_get_property;
  gobject_class->set_property = hello_world_service_say_hello_result_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_HELLO_WORLD_SERVICE_SAY_HELLO_RESULT_SUCCESS,
     g_param_spec_string ("success",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));
}

GType
hello_world_service_say_hello_result_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (HelloWorldServiceSayHelloResultClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) hello_world_service_say_hello_result_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (HelloWorldServiceSayHelloResult),
      0, /* n_preallocs */
      (GInstanceInitFunc) hello_world_service_say_hello_result_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "HelloWorldServiceSayHelloResultType",
                                   &type_info, 0);
  }

  return type;
}

