/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HELLOWORLD_TYPES_H
#define HELLOWORLD_TYPES_H

/* base includes */
#include <glib-object.h>
#include <thrift/c_glib/thrift_struct.h>
#include <thrift/c_glib/protocol/thrift_protocol.h>
/* custom thrift includes */

/* begin types */

/* constants */

/* struct HelloWorldServiceSayHelloArgs */
struct _HelloWorldServiceSayHelloArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * name;
  gboolean __isset_name;
};
typedef struct _HelloWorldServiceSayHelloArgs HelloWorldServiceSayHelloArgs;

struct _HelloWorldServiceSayHelloArgsClass
{
  ThriftStructClass parent;
};
typedef struct _HelloWorldServiceSayHelloArgsClass HelloWorldServiceSayHelloArgsClass;

GType hello_world_service_say_hello_args_get_type (void);
#define TYPE_HELLO_WORLD_SERVICE_SAY_HELLO_ARGS (hello_world_service_say_hello_args_get_type())
#define HELLO_WORLD_SERVICE_SAY_HELLO_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_HELLO_WORLD_SERVICE_SAY_HELLO_ARGS, HelloWorldServiceSayHelloArgs))
#define HELLO_WORLD_SERVICE_SAY_HELLO_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_HELLO_WORLD_SERVICE_SAY_HELLO_ARGS, HelloWorldServiceSayHelloArgsClass))
#define IS_HELLO_WORLD_SERVICE_SAY_HELLO_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_HELLO_WORLD_SERVICE_SAY_HELLO_ARGS))
#define IS_HELLO_WORLD_SERVICE_SAY_HELLO_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_HELLO_WORLD_SERVICE_SAY_HELLO_ARGS))
#define HELLO_WORLD_SERVICE_SAY_HELLO_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_HELLO_WORLD_SERVICE_SAY_HELLO_ARGS, HelloWorldServiceSayHelloArgsClass))

/* struct HelloWorldServiceSayHelloResult */
struct _HelloWorldServiceSayHelloResult
{ 
  ThriftStruct parent; 

  /* public */
  gchar * success;
  gboolean __isset_success;
};
typedef struct _HelloWorldServiceSayHelloResult HelloWorldServiceSayHelloResult;

struct _HelloWorldServiceSayHelloResultClass
{
  ThriftStructClass parent;
};
typedef struct _HelloWorldServiceSayHelloResultClass HelloWorldServiceSayHelloResultClass;

GType hello_world_service_say_hello_result_get_type (void);
#define TYPE_HELLO_WORLD_SERVICE_SAY_HELLO_RESULT (hello_world_service_say_hello_result_get_type())
#define HELLO_WORLD_SERVICE_SAY_HELLO_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_HELLO_WORLD_SERVICE_SAY_HELLO_RESULT, HelloWorldServiceSayHelloResult))
#define HELLO_WORLD_SERVICE_SAY_HELLO_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_HELLO_WORLD_SERVICE_SAY_HELLO_RESULT, HelloWorldServiceSayHelloResultClass))
#define IS_HELLO_WORLD_SERVICE_SAY_HELLO_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_HELLO_WORLD_SERVICE_SAY_HELLO_RESULT))
#define IS_HELLO_WORLD_SERVICE_SAY_HELLO_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_HELLO_WORLD_SERVICE_SAY_HELLO_RESULT))
#define HELLO_WORLD_SERVICE_SAY_HELLO_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_HELLO_WORLD_SERVICE_SAY_HELLO_RESULT, HelloWorldServiceSayHelloResultClass))

#endif /* HELLOWORLD_TYPES_H */
